# Generated by Django 5.2.7 on 2025-12-16 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.school')),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'unique_together': {('name', 'school')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=30, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('session', models.CharField(blank=True, max_length=20, null=True)),
                ('term', models.CharField(blank=True, choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], default='', max_length=1)),
                ('is_result_blocked', models.BooleanField(default=False)),
                ('block_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promoted_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_from', to='students.schoolclass')),
                ('promoted_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_to', to='students.schoolclass')),
                ('school', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.school')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.schoolclass')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20)),
                ('promoted_on', models.DateTimeField(auto_now_add=True)),
                ('new_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_new', to='students.schoolclass')),
                ('old_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_old', to='students.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_records', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='cumulative_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20)),
                ('total_first', models.FloatField(default=0)),
                ('total_second', models.FloatField(default=0)),
                ('total_third', models.FloatField(default=0)),
                ('cumulative_average', models.FloatField(default=0)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'unique_together': {('student', 'session')},
            },
        ),
    ]
