# Generated by Django 5.2.7 on 2026-01-25 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_school_paystack_public_key_and_more'),
        ('students', '0002_alter_schoolclass_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='paystack_customer_code',
            field=models.CharField(blank=True, help_text='Paystack customer code', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='virtual_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='virtual_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='virtual_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='virtual_bank_slug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_no',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='promoted_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_from_students', to='students.schoolclass'),
        ),
        migrations.AlterField(
            model_name='student',
            name='promoted_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_to_students', to='students.schoolclass'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(blank=True, help_text='Current class of the student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.schoolclass'),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.CharField(blank=True, help_text='Current academic session', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='term',
            field=models.CharField(blank=True, choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=1, null=True),
        ),
    ]
