# Generated by Django 5.2.7 on 2025-10-28 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_admission_no_student_admission_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='admission_number',
            new_name='admission_no',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='date_of_birth',
            new_name='dob',
        ),
    ]
