# Generated by Django 5.2.7 on 2025-11-14 18:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_school_options_school_active_school_created_on_and_more'),
        ('students', '0003_rename_admission_number_student_admission_no_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='term',
            field=models.CharField(blank=True, choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], default='', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('name', 'school')},
        ),
        migrations.DeleteModel(
            name='student_profile_ext',
        ),
    ]
