# Generated by Django 5.2.7 on 2026-01-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_paystack_customer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='va_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
