# Generated by Django 5.2.7 on 2026-01-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_va_verified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='virtual_account_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
