# Generated by Django 5.2.7 on 2025-12-07 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_block_reason_student_is_result_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='session',
        ),
        migrations.RemoveField(
            model_name='student',
            name='term',
        ),
        migrations.AlterField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.schoolclass'),
        ),
    ]
