# Generated by Django 5.2.7 on 2026-01-29 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_virtual_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='va_verified_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='virtual_account_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='virtual_account_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='virtual_bank_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='virtual_bank_slug',
        ),
        migrations.CreateModel(
            name='VirtualAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_slug', models.CharField(db_index=True, max_length=50)),
                ('is_primary', models.BooleanField(default=False, help_text='Preferred account to show first on dashboard')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_accounts', to='students.student')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
