# Generated by Django 5.2.7 on 2025-12-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_student_session_remove_student_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='term',
            field=models.CharField(blank=True, choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], default='', max_length=1),
        ),
    ]
