# Generated by Django 5.2.7 on 2026-04-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_migrate_old_va_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive students cannot login to the portal'),
        ),
    ]
