# Generated by Django 5.2.7 on 2025-12-12 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_session_student_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='promoted_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_from', to='students.schoolclass'),
        ),
        migrations.AddField(
            model_name='student',
            name='promoted_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_to', to='students.schoolclass'),
        ),
        migrations.CreateModel(
            name='PromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20)),
                ('promoted_on', models.DateTimeField(auto_now_add=True)),
                ('new_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_new', to='students.schoolclass')),
                ('old_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_old', to='students.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_records', to='students.student')),
            ],
        ),
    ]
