# Generated by Django 5.2.7 on 2026-05-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_announcement_school_class_announcement_send_channel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='school_class',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='send_channel',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='student',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='target',
        ),
        migrations.AddField(
            model_name='announcement',
            name='school_classes',
            field=models.ManyToManyField(blank=True, related_name='announcement_classes', to='students.schoolclass'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='send_channels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='announcement',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='announcement_students', to='students.student'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='targets',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
