# Generated by Django 5.2.7 on 2026-05-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_remove_announcement_school_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='send_email',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='send_whatsapp',
        ),
    ]
