# Generated by Django 5.2.7 on 2026-05-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_remove_announcement_send_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCommunicationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('smtp_sender_name', models.CharField(blank=True, max_length=255)),
                ('smtp_sender_email', models.EmailField(blank=True, max_length=254)),
                ('brevo_api_key', models.CharField(max_length=255)),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('whatsapp_token', models.TextField(blank=True)),
                ('whatsapp_phone_id', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
