# Generated by Django 5.2.7 on 2026-05-20 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_globalcommunicationsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolCommunicationSetting',
        ),
    ]
