# Generated by Django 5.2.7 on 2026-06-06 21:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_delete_schoolcommunicationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
