# Generated by Django 5.2.7 on 2026-06-06 21:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_student_student_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
