# Generated by Django 5.2.7 on 2026-09-20 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_school_principal_name_school_school_stamp'),
        ('students', '0016_alter_student_student_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_classes', to='accounts.teacher'),
        ),
    ]
