# Generated by Django 5.2.7 on 2026-02-15 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_school_paystack_public_key_and_more'),
        ('results', '0005_resultcomment_is_locked'),
        ('students', '0007_migrate_old_va_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('room_name', models.CharField(max_length=255, unique=True)),
                ('room_password', models.CharField(editable=False, max_length=12, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.schoolclass')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='accounts.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='results.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='accounts.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='LiveClassAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='liveclass.liveclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_class_attendance', to='students.student')),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('live_class', 'student')},
            },
        ),
    ]
