# Generated by Django 5.2.7 on 2026-02-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liveclass',
            options={'ordering': ['-start_time']},
        ),
        migrations.RemoveField(
            model_name='liveclass',
            name='room_name',
        ),
        migrations.RemoveField(
            model_name='liveclass',
            name='room_password',
        ),
        migrations.AddField(
            model_name='liveclass',
            name='camera_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='youtube_link',
            field=models.URLField(default='https://www.youtube.com/embed/YOUR_GLOBAL_LIVE_LINK', help_text='Global YouTube live link for all schools'),
        ),
    ]
