# Generated by Django 5.2.7 on 2026-02-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0002_alter_liveclass_options_remove_liveclass_room_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveclass',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='liveclass',
            name='hms_room_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
