# Generated by Django 5.2.7 on 2026-03-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0003_remove_liveclass_youtube_link_liveclass_hms_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liveclass',
            old_name='hms_room_id',
            new_name='room_id',
        ),
    ]
