# Generated by Django 5.2.7 on 2026-04-14 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0004_rename_hms_room_id_liveclass_room_id'),
        ('students', '0007_migrate_old_va_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClassWaiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list', to='liveclass.liveclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_classes', to='students.student')),
            ],
            options={
                'ordering': ['requested_at'],
                'unique_together': {('live_class', 'student')},
            },
        ),
    ]
