# Generated by Django 5.2.7 on 2026-04-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0005_liveclasswaiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclasswaiting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
