# Generated by Django 5.2.7 on 2026-04-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0006_liveclasswaiting_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='recording_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='recording_status',
            field=models.CharField(default='idle', max_length=50),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='recording_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
