# Generated by Django 5.2.7 on 2026-08-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0007_liveclass_recording_id_liveclass_recording_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='recording_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
