# Generated by Django 5.2.7 on 2026-09-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0008_alter_liveclass_recording_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclasswaiting',
            name='breakout_room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='liveclasswaiting',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liveclasswaiting',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
