# Generated by Django 5.2.7 on 2026-09-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0009_liveclasswaiting_breakout_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclasswaiting',
            name='breakout_room_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
