# Generated by Django 5.2.7 on 2026-09-16 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass', '0010_liveclasswaiting_breakout_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='allow_guest_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='event_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='event_slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='guest_max_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='liveclass_type',
            field=models.CharField(choices=[('school_class', 'School Class'), ('public_event', 'Public Event')], db_index=True, default='school_class', max_length=20),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='record_public_event',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LiveClassGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_guests', to='liveclass.liveclass')),
            ],
        ),
    ]
