# Generated by Django 5.2.7 on 2026-09-17 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_school_principal_name_school_school_stamp'),
        ('liveclass', '0011_liveclass_allow_guest_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='accounts.teacher'),
        ),
    ]
