# Generated by Django 5.2.7 on 2026-10-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_school_principal_name_school_school_stamp'),
        ('liveclass', '0012_alter_liveclass_teacher'),
        ('results', '0007_classscoresetting_show_position'),
        ('students', '0017_schoolclass_class_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveclass',
            name='class_room',
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('ended', 'Ended')], default='upcoming', max_length=20),
        ),
        migrations.RemoveField(
            model_name='liveclass',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='liveclass',
            name='teacher',
        ),
        migrations.AddField(
            model_name='liveclass',
            name='class_room',
            field=models.ManyToManyField(related_name='live_classes', to='students.schoolclass'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='subject',
            field=models.ManyToManyField(related_name='live_classes', to='results.subject'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='live_classes', to='accounts.teacher'),
        ),
    ]
