# Generated by Django 5.2.7 on 2025-11-14 18:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_school_options_school_active_school_created_on_and_more'),
        ('finance', '0001_initial'),
        ('students', '0004_alter_schoolclass_options_student_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='fee_structure',
            options={'ordering': ['class_assigned__name']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='expense',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='fee_structure',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='fee_structure',
            name='session',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fee_structure',
            name='term',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='term',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='accounts.school'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='fee_structure',
            unique_together={('school', 'class_assigned', 'description', 'session', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('school', 'name', 'session')},
        ),
    ]
