# Generated by Django 5.2.7 on 2025-11-15 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_school_options_school_active_school_created_on_and_more'),
        ('finance', '0002_alter_expense_options_alter_fee_structure_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAccountSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.school')),
            ],
        ),
    ]
