# Generated by Django 5.2.7 on 2026-01-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_payment_recorded_by_schooltermsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooltermsetting',
            name='next_term_begins',
            field=models.DateField(blank=True, null=True),
        ),
    ]
