# Generated by Django 5.2.7 on 2025-11-23 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_schooladmin'),
        ('finance', '0003_expensecategory_schoolaccountsummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, help_text='School this accountant belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountants', to='accounts.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accountant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accountant',
                'verbose_name_plural': 'Accountants',
            },
        ),
    ]
