# Generated by Django 5.2.7 on 2026-01-19 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_school_paystack_public_key_and_more'),
        ('finance', '0005_paystacktransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.school'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reference'], name='finance_pay_referen_f3a360_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['school'], name='finance_pay_school__ad0254_idx'),
        ),
    ]
