# Generated by Django 5.2.7 on 2025-12-14 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_school_theme_color'),
        ('finance', '0005_schoolaccountant_delete_accountant'),
        ('students', '0008_student_promoted_from_student_promoted_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fee_structure',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='fee_structure',
            name='class_assigned',
        ),
        migrations.RemoveField(
            model_name='fee_structure',
            name='school',
        ),
        migrations.RemoveField(
            model_name='schoolaccountsummary',
            name='school',
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='term',
            name='school',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='term',
            field=models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], default='', max_length=1),
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='note',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='note',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reference',
        ),
        migrations.AddField(
            model_name='expense',
            name='school_class',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='students.schoolclass'),
        ),
        migrations.AddField(
            model_name='expense',
            name='session',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='term',
            field=models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='invoice',
            name='school_class',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='students.schoolclass'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='session',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='school_class',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='students.schoolclass'),
        ),
        migrations.AddField(
            model_name='payment',
            name='session',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='term',
            field=models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.school'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.school'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.school'),
        ),
        migrations.CreateModel(
            name='FeeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_templates', to='accounts.school')),
                ('school_class', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='students.schoolclass')),
            ],
            options={
                'unique_together': {('school', 'school_class', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('session', models.CharField(default='', max_length=20)),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], default='', max_length=1)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.payment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.school')),
                ('school_class', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='students.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('title', models.CharField(default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('session', models.CharField(choices=[('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025')], default='', max_length=20)),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], default='', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.school')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
        migrations.DeleteModel(
            name='fee_structure',
        ),
        migrations.DeleteModel(
            name='SchoolAccountSummary',
        ),
        migrations.DeleteModel(
            name='Term',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='note',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
    ]
