# Generated by Django 5.2.7 on 2025-12-14 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_fee_structure_unique_together_and_more'),
        ('students', '0008_student_promoted_from_student_promoted_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.schoolclass'),
        ),
    ]
