# Generated by Django 5.2.7 on 2026-01-19 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_school_paystack_public_key_and_more'),
        ('finance', '0006_payment_reference_alter_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystacktransaction',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paystack_transactions', to='accounts.school'),
        ),
        migrations.AddIndex(
            model_name='paystacktransaction',
            index=models.Index(fields=['status'], name='finance_pay_status_91649f_idx'),
        ),
    ]
