# Generated by Django 5.2.7 on 2026-01-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
