# Generated by Django 5.2.7 on 2026-01-21 19:40

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_school_paystack_public_key_and_more'),
        ('finance', '0010_alter_payment_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='finance_pay_school__ad0254_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Raw gateway metadata (Paystack, Moniepoint, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(help_text='Gateway reference or internal transaction ID', max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['school', 'payment_method'], name='finance_pay_school__4742eb_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'payment_date'], name='finance_pay_invoice_8fca2f_idx'),
        ),
    ]
