# Generated by Django 5.2.7 on 2026-01-24 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_school_paystack_public_key_and_more'),
        ('finance', '0011_remove_payment_finance_pay_school__ad0254_idx_and_more'),
        ('students', '0002_alter_schoolclass_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.schoolclass'),
        ),
        migrations.AddField(
            model_name='payment',
            name='session',
            field=models.CharField(blank=True, help_text='Academic session for this payment', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='approved', help_text='Status of the payment', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student'),
        ),
        migrations.AddField(
            model_name='payment',
            name='term',
            field=models.CharField(blank=True, help_text='Academic term for this payment', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'term', 'session'], name='finance_pay_student_65e110_idx'),
        ),
    ]
