# Generated by Django 5.2.7 on 2026-02-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_payment_school_class_payment_session_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, help_text='Gateway reference or internal transaction ID', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('voided', 'Voided'), ('reversed', 'Reversed')], default='approved', help_text='Current status of the payment', max_length=20),
        ),
    ]
