# Generated by Django 5.2.7 on 2026-02-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_payment_reference_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystacktransaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
