# Generated by Django 5.2.7 on 2026-08-03 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_paystacktransaction_metadata'),
        ('tis_website', '0002_admissionapplication_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='admission_application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_invoice', to='tis_website.admissionapplication'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_admission_fee',
            field=models.BooleanField(default=False),
        ),
    ]
