# Generated by Django 5.2.7 on 2026-08-03 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_invoice_admission_application_and_more'),
        ('tis_website', '0002_admissionapplication_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='admission_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_invoice', to='tis_website.admissionapplication'),
        ),
    ]
