# Generated by Django 5.2.7 on 2026-08-03 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_alter_invoice_admission_application'),
        ('students', '0016_alter_student_student_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='students.student'),
        ),
    ]
