# Generated by Django 5.2.7 on 2026-07-28 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Welcome to Tech International School', max_length=200)),
                ('hero_subtitle', models.TextField(default='Building Future Leaders Through Technology, Innovation and Excellence')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='website/homepage/')),
                ('primary_button_text', models.CharField(default='Apply Now', max_length=50)),
                ('primary_button_link', models.CharField(default='/school/admissions/', max_length=200)),
                ('secondary_button_text', models.CharField(default='Student Portal', max_length=50)),
                ('secondary_button_link', models.CharField(default='/accounts/login/', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homepage', to='accounts.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=1)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='accounts.school')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SchoolWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motto', models.CharField(max_length=255)),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
                ('history', models.TextField()),
                ('principal_name', models.CharField(max_length=200)),
                ('principal_photo', models.ImageField(upload_to='website/principal/')),
                ('principal_message', models.TextField()),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website', to='accounts.school')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose', to='accounts.school')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
