# Generated by Django 5.2.7 on 2026-08-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tis_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
