# Generated by Django 5.2.7 on 2026-07-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tis_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolwebsite',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolwebsite',
            name='principal_photo',
            field=models.ImageField(blank=True, null=True, upload_to='website/principal/'),
        ),
    ]
