# Generated by Django 5.2.7 on 2026-08-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tis_website', '0002_admissionapplication_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('exam_assigned', 'Exam Assigned'), ('exam_completed', 'Exam Completed'), ('passed', 'Passed'), ('failed', 'Failed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=30),
        ),
    ]
