# Generated by Django 5.2.7 on 2026-08-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tis_website', '0003_alter_admissionapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionapplication',
            name='admission_term',
            field=models.CharField(blank=True, choices=[('1', 'First Term'), ('2', 'Second Term'), ('3', 'Third Term')], max_length=50),
        ),
    ]
