# Generated by Django 5.2.7 on 2025-12-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.CharField(blank=True, help_text='Path relative to static/, e.g. img/schools/my_school.png', max_length=255),
        ),
    ]
