# Generated by Django 5.2.7 on 2025-10-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='stamp',
        ),
        migrations.AddField(
            model_name='school',
            name='principal_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
