# Generated by Django 5.2.7 on 2025-12-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_school_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={},
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload school logo (Cloudinary)', null=True, upload_to='school_logos/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='theme_color',
            field=models.CharField(choices=[('indigo', 'Indigo'), ('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('pink', 'Pink'), ('teal', 'Teal'), ('gray', 'Gray')], default='indigo', max_length=20),
        ),
    ]
