# Generated by Django 5.2.7 on 2025-12-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_schooladmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='theme_color',
            field=models.CharField(choices=[('indigo', 'Indigo'), ('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('pink', 'Pink'), ('teal', 'Teal'), ('gray', 'Gray')], default='indigo', help_text='Primary theme color used across the school portal', max_length=20),
        ),
    ]
