# Generated by Django 5.2.7 on 2026-01-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20260106_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='paystack_public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='paystack_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
