# Generated by Django 5.2.7 on 2026-05-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='email_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='notification_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
