# Generated by Django 5.2.7 on 2026-05-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_school_email_enabled_school_notification_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='email_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
