# Generated by Django 5.2.7 on 2026-07-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='admission_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
