# Generated by Django 5.2.7 on 2026-08-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_school_admission_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='admission_prefix',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
