# Generated by Django 5.2.7 on 2026-08-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_school_admission_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='principal_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='school',
            name='school_stamp',
            field=models.ImageField(blank=True, null=True, upload_to='school/stamps/'),
        ),
    ]
