# Generated by Django 5.2.7 on 2025-12-16 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('results', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('session', models.CharField(blank=True, max_length=20, null=True)),
                ('term', models.CharField(blank=True, choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=1, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson_notes/')),
                ('visibility', models.CharField(choices=[('all', 'All Students'), ('classes', 'Specific Classes'), ('private', 'Only Me (Teacher)')], default='all', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('classes', models.ManyToManyField(blank=True, help_text="If visibility is 'Specific Classes', choose classes.", to='students.schoolclass')),
                ('school', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_notes', to='accounts.school')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='results.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_notes', to='accounts.teacher')),
            ],
            options={
                'verbose_name': 'Lesson Note',
                'verbose_name_plural': 'Lesson Notes',
                'ordering': ('-publish_date', '-created_on'),
            },
        ),
        migrations.CreateModel(
            name='LessonNoteSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('graded_on', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('draft', 'Draft'), ('graded', 'Graded'), ('late', 'Late')], default='submitted', max_length=20)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teacher')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='notes.lessonnote')),
                ('school', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='note_submissions', to='accounts.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_submissions', to='students.student')),
            ],
            options={
                'verbose_name': 'Lesson Note Submission',
                'verbose_name_plural': 'Lesson Note Submissions',
                'ordering': ['-submitted_on'],
                'unique_together': {('note', 'student')},
            },
        ),
        migrations.CreateModel(
            name='NoteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('school', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='note_categories', to='accounts.school')),
            ],
            options={
                'verbose_name': 'Note Category',
                'verbose_name_plural': 'Note Categories',
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.notecategory'),
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='notes/submissions/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='notes.lessonnotesubmission')),
            ],
        ),
    ]
