# Generated by Django 5.2.7 on 2026-07-22 13:47

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_subscribe'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonnote',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Leave blank if the lesson note should never expire.', null=True),
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive notes are hidden from students.'),
        ),
        migrations.AlterField(
            model_name='lessonnote',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='lesson_notes/'),
        ),
        migrations.AlterField(
            model_name='lessonnote',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_notes', to='accounts.school'),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='notes/submissions/'),
        ),
    ]
