# Generated by Django 5.2.7 on 2026-09-25 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_lessonnote_expiry_date_lessonnote_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonnote',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lesson_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='week',
            field=models.CharField(blank=True, choices=[('1', 'Week 1'), ('2', 'Week 2'), ('3', 'Week 3'), ('4', 'Week 4'), ('5', 'Week 5'), ('6', 'Week 6'), ('7', 'Week 7'), ('8', 'Week 8'), ('9', 'Week 9'), ('10', 'Week 10'), ('11', 'Week 11'), ('12', 'Week 12'), ('13', 'Week 13'), ('14', 'Week 14')], help_text='Select the teaching week.', max_length=2, null=True),
        ),
    ]
