# Generated by Django 5.2.7 on 2025-11-14 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_school_options_school_active_school_created_on_and_more'),
        ('notes', '0002_lessonnote_session_lessonnote_term'),
        ('students', '0004_alter_schoolclass_options_student_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonnote',
            options={'ordering': ('-publish_date', '-created_on'), 'verbose_name': 'Lesson Note', 'verbose_name_plural': 'Lesson Notes'},
        ),
        migrations.AlterModelOptions(
            name='lessonnotesubmission',
            options={'ordering': ['-submitted_on'], 'verbose_name': 'Lesson Note Submission', 'verbose_name_plural': 'Lesson Note Submissions'},
        ),
        migrations.AlterModelOptions(
            name='notecategory',
            options={'ordering': ['name'], 'verbose_name': 'Note Category', 'verbose_name_plural': 'Note Categories'},
        ),
        migrations.AddField(
            model_name='lessonnote',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_notes', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='lessonnotesubmission',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='note_submissions', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='notecategory',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='note_categories', to='accounts.school'),
        ),
        migrations.AlterField(
            model_name='lessonnote',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_notes', to='accounts.teacher'),
        ),
        migrations.AlterField(
            model_name='lessonnotesubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teacher'),
        ),
        migrations.AlterField(
            model_name='lessonnotesubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_submissions', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='notecategory',
            unique_together={('school', 'name')},
        ),
    ]
