# Generated by Django 5.2.7 on 2025-12-13 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_school_theme_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPortalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbt_enabled', models.BooleanField(default=True)),
                ('results_enabled', models.BooleanField(default=True)),
                ('lesson_note_enabled', models.BooleanField(default=True)),
                ('attendance_enabled', models.BooleanField(default=True)),
                ('finance_enabled', models.BooleanField(default=True)),
                ('teachers_enabled', models.BooleanField(default=True)),
                ('students_enabled', models.BooleanField(default=True)),
                ('assignments_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_settings', to='accounts.school')),
            ],
        ),
    ]
