# Generated by Django 5.2.7 on 2026-05-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolportalsetting',
            name='announcement_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
