# Generated by Django 5.2.7 on 2026-05-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_schoolportalsetting_announcement_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolportalsetting',
            name='liveclass_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
