# Generated by Django 5.2.7 on 2026-08-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_schoolportalsetting_liveclass_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolportalsetting',
            name='visitSchoolWebsite_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolportalsetting',
            name='websiteManagement_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
