# Generated by Django 5.2.7 on 2026-07-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignment_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='assignment',
            name='expiry_date',
            field=models.DateTimeField(blank=True, help_text='Assignment will disappear after this date.', null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
