# Generated by Django 5.2.7 on 2025-11-14 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_school_options_school_active_school_created_on_and_more'),
        ('assignments', '0003_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.school'),
        ),
    ]
