# Generated by Django 5.2.7 on 2025-11-17 20:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_school_options_school_active_school_created_on_and_more'),
        ('students', '0004_alter_schoolclass_options_student_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBTExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('session', models.CharField(default='', max_length=20)),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], default='', max_length=1)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to='accounts.teacher')),
                ('school', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cbt_exams', to='accounts.school')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.schoolclass')),
            ],
            options={
                'verbose_name': 'CBT Exam',
                'verbose_name_plural': 'CBT Exams',
                'db_table': 'CBTExam',
            },
        ),
        migrations.CreateModel(
            name='CBTQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('option_a', models.CharField(max_length=400)),
                ('option_b', models.CharField(max_length=400)),
                ('option_c', models.CharField(blank=True, max_length=400)),
                ('option_d', models.CharField(blank=True, max_length=400)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('marks', models.IntegerField(default=1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cbt.cbtexam')),
            ],
            options={
                'verbose_name': 'CBT Question',
                'verbose_name_plural': 'CBT Questions',
                'db_table': 'CBTQuestion',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('exam_duration', models.IntegerField(default=30, help_text='Default duration in minutes')),
                ('school', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cbt_subjects', to='accounts.school')),
            ],
            options={
                'verbose_name_plural': 'CBT Subjects',
                'unique_together': {('name', 'school')},
            },
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt.subject'),
        ),
        migrations.CreateModel(
            name='CBTSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('started_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('raw_answers', models.JSONField(default=dict)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt.cbtexam')),
                ('school', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cbt_submissions', to='accounts.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'verbose_name': 'CBT Submission',
                'verbose_name_plural': 'CBT Submissions',
                'db_table': 'CBTSubmission',
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
