# Generated by Django 5.2.7 on 2025-12-27 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_contactmessage'),
        ('cbt', '0001_initial'),
        ('results', '0002_alter_score_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('option_a', models.CharField(max_length=400)),
                ('option_b', models.CharField(max_length=400)),
                ('option_c', models.CharField(blank=True, max_length=400)),
                ('option_d', models.CharField(blank=True, max_length=400)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to='accounts.teacher')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank', to='accounts.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank', to='results.subject')),
            ],
            options={
                'db_table': 'QuestionBank',
                'ordering': ['-created_at'],
            },
        ),
    ]
