# Generated by Django 5.2.7 on 2025-12-15 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0001_initial'),
        ('results', '0018_subject_code_subject_exam_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbtexam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='results.subject'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
