# Generated by Django 5.2.7 on 2025-12-27 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0002_questionbank'),
        ('students', '0002_alter_schoolclass_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_bank', to='students.schoolclass'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='session',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='term',
            field=models.CharField(blank=True, choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], max_length=1),
        ),
    ]
