# Generated by Django 5.2.7 on 2026-01-07 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20260106_0616'),
        ('cbt', '0003_questionbank_school_class_questionbank_session_and_more'),
        ('results', '0005_resultcomment_is_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='accounts.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='results.subject')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('school', 'subject', 'name')},
            },
        ),
        migrations.AddField(
            model_name='questionbank',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='cbt.topic'),
        ),
    ]
