# Generated by Django 5.2.7 on 2026-01-08 14:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0004_topic_questionbank_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbtquestion',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
