# Generated by Django 5.2.7 on 2026-01-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0005_alter_cbtquestion_text_alter_questionbank_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtquestion',
            name='equation',
            field=models.TextField(blank=True, help_text='Raw LaTeX only, e.g. x^2 + 4x + 4 = 0'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='equation',
            field=models.TextField(blank=True, help_text='Raw LaTeX only, e.g. x^2 + 4x + 4 = 0'),
        ),
    ]
