# Generated by Django 5.2.7 on 2026-01-16 11:13

from django.db import migrations



from django.db import migrations


def normalize_questions_and_options(apps, schema_editor):
    CBTQuestion = apps.get_model("cbt", "CBTQuestion")

    # Import your utility
    from results.utils import normalize_latex_in_html

    for q in CBTQuestion.objects.all():
        changed = False

        # Normalize question text
        if q.text:
            normalized_text = normalize_latex_in_html(q.text)
            if normalized_text != q.text:
                q.text = normalized_text
                changed = True

        # Normalize question equation
        if q.equation:
            normalized_eq = normalize_latex_in_html(q.equation)
            if normalized_eq != q.equation:
                q.equation = normalized_eq
                changed = True

        # Normalize options A–D
        for field in ["option_a", "option_b", "option_c", "option_d"]:
            value = getattr(q, field, None)
            if value:
                normalized = normalize_latex_in_html(value)
                if normalized != value:
                    setattr(q, field, normalized)
                    changed = True

        if changed:
            q.save(update_fields=["text", "equation", "option_a", "option_b", "option_c", "option_d"])


def reverse_noop(apps, schema_editor):
    """Irreversible migration by design"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("cbt", "0006_cbtquestion_equation_questionbank_equation"),  # ⚠️ Replace with your actual last migration
    ]

    operations = [
        migrations.RunPython(normalize_questions_and_options, reverse_noop),
    ]



