# Generated by Django 5.2.7 on 2026-02-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0007_normalize_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='diagram',
            field=models.ImageField(blank=True, null=True, upload_to='question_bank/diagrams/'),
        ),
    ]
