# Generated by Django 5.2.7 on 2026-02-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0008_questionbank_diagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtquestion',
            name='diagram',
            field=models.ImageField(blank=True, null=True, upload_to='cbt/diagrams/'),
        ),
    ]
