# Generated by Django 5.2.7 on 2026-02-12 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0009_cbtquestion_diagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtquestion',
            name='source_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbt.questionbank'),
        ),
    ]
