# Generated by Django 5.2.7 on 2026-02-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0010_cbtquestion_source_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtexam',
            name='allow_calculator',
            field=models.BooleanField(default=False),
        ),
    ]
