# Generated by Django 5.2.7 on 2026-02-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0011_cbtexam_allow_calculator'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtquestion',
            name='option_a_diagram',
            field=models.ImageField(blank=True, null=True, upload_to='cbt/options/'),
        ),
        migrations.AddField(
            model_name='cbtquestion',
            name='option_a_equation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cbtquestion',
            name='option_b_diagram',
            field=models.ImageField(blank=True, null=True, upload_to='cbt/options/'),
        ),
        migrations.AddField(
            model_name='cbtquestion',
            name='option_b_equation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cbtquestion',
            name='option_c_diagram',
            field=models.ImageField(blank=True, null=True, upload_to='cbt/options/'),
        ),
        migrations.AddField(
            model_name='cbtquestion',
            name='option_c_equation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cbtquestion',
            name='option_d_diagram',
            field=models.ImageField(blank=True, null=True, upload_to='cbt/options/'),
        ),
        migrations.AddField(
            model_name='cbtquestion',
            name='option_d_equation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='option_a_diagram',
            field=models.ImageField(blank=True, null=True, upload_to='question_bank/options/'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='option_a_equation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='option_b_diagram',
            field=models.ImageField(blank=True, null=True, upload_to='question_bank/options/'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='option_b_equation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='option_c_diagram',
            field=models.ImageField(blank=True, null=True, upload_to='question_bank/options/'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='option_c_equation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='option_d_diagram',
            field=models.ImageField(blank=True, null=True, upload_to='question_bank/options/'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='option_d_equation',
            field=models.TextField(blank=True),
        ),
    ]
