# Generated by Django 5.2.7 on 2026-03-02 19:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0012_cbtquestion_option_a_diagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbtquestion',
            name='option_a',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='cbtquestion',
            name='option_b',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='cbtquestion',
            name='option_c',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cbtquestion',
            name='option_d',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='option_a',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='option_b',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='option_c',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='option_d',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
