# Generated by Django 5.2.7 on 2026-07-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0013_alter_cbtquestion_option_a_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cbtsubmission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='exam_type',
            field=models.CharField(choices=[('academic', 'Academic Exam'), ('admission', 'Admission Exam')], default='academic', max_length=20),
        ),
    ]
