# Generated by Django 5.2.7 on 2026-07-31 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_school_admission_fee'),
        ('cbt', '0014_alter_cbtsubmission_unique_together_and_more'),
        ('students', '0016_alter_student_student_uuid'),
        ('tis_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtsubmission',
            name='admission_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cbt_attempts', to='tis_website.admissionapplication'),
        ),
        migrations.AlterField(
            model_name='cbtsubmission',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cbt_submissions', to='accounts.school'),
        ),
        migrations.AlterField(
            model_name='cbtsubmission',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddConstraint(
            model_name='cbtsubmission',
            constraint=models.UniqueConstraint(fields=('student', 'exam'), name='unique_student_exam'),
        ),
        migrations.AddConstraint(
            model_name='cbtsubmission',
            constraint=models.UniqueConstraint(fields=('admission_candidate', 'exam'), name='unique_admission_exam'),
        ),
    ]
