# Generated by Django 5.2.7 on 2026-08-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0015_cbtsubmission_admission_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtexam',
            name='pass_mark',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Minimum percentage required to pass this exam', max_digits=5),
        ),
    ]
